import "@/styles/globals.css"
import {Inter as FontSans} from "next/font/google"
import {cn} from "@/lib/utils";
import {Metadata} from "next";
import {Locale} from "../../../i18n.config";
import Providers from "@/components/global/Providers";
import {ReactNode} from "react";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: 'Boilerplate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
  children: ReactNode,
  params: {lang: Locale}
}) {
  return (
    <html lang={params.lang} suppressHydrationWarning>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
